---
# Playbook to configure Kali VM
- hosts: kali
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: true
        upgrade: safe
  
    - name: Install packages
      apt:
        name: "{{ kali_packages }}"
        state: latest

# Install extra apps and files
- hosts: kali
  roles:
    - ansible-role-chromium
    - ansible-role-empire
    - ansible-role-hcxdumptool
    - ansible-role-hcxtools
    - ansible-role-nullinux
    - ansible-role-vscode
  tasks:
    - name: Clone git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
      loop: "{{ git_repos | flatten(levels=1) }}"

    - name: Enable Postgresql service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Check msfdb status
      command: msfdb status
      register: msfdb_status

    - name: Initialize msfdb
      command: msfdb init
      when: "'No configuration file found' in msfdb_status.stdout"

    - name: Configure OpenSSL
      lineinfile:
        path: /etc/ssl/openssl.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: "^MinProtocol ="
          line: "MinProtocol = None"
        - regexp: "^CipherStrings ="
          line: "CipherStrings = DEFAULT"
