---
# Playbook for Kali

## Personalize Kali
- hosts: kali
  become: true
  roles:
    - ansible-role-vscode
  tasks:
    ## Configure Gnome settings ##
    - name: Tweak Gnome settings
      command: "gsettings set {{ item }}"
      loop:
        - "{{ gnome_settings }}"

    - name: Get current terminal profile
      command: gsettings get org.gnome.Terminal.ProfilesList default
      changed_when: false
      register: terminal_profile

    - name: Configure Terminal settings
      command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${TERM_PROFILE:1:-1}/ use-transparent-background false"
      environment:
        TERM_PROFILE: terminal_profile.stdout

    ## Configure tmux ##
    - name: Copy tmux config
      copy:
        src: files/.tmux.conf
        dest: "/home/{{ kali_user }}/.tmux.conf"
        owner: "{{ kali_user }}"
        group: "{{ kali_user }}"
        mode: 0640
