---
# Playbook for Kali

## Personalize Kali
- hosts: kali
  roles:
    - role: ansible-role-vscode
      become: true
  tasks:
    ### Configure Gnome settings ###
    - name: Tweak Gnome settings
      command: "gsettings set {{ item }}"
      loop: "{{ gnome_settings }}"

    - name: Get current terminal profile
      command: gsettings get org.gnome.Terminal.ProfilesList default
      changed_when: false
      register: terminal_profile

    # Disable terminal background transparency
    - name: Configure Terminal settings
      command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout | regex_replace('''') }}/ use-transparent-background false"

    ### Accept Burp Suite agreement ###
    - name: Accept Burp Suite agreement/license
      command: "python3 license_burp.py {{ burpsuite_product_type }} {{ burpsuite_dir }}"
      args:
        chdir: "{{ burpsuite_extras_dir }}"
      register: license_burp
      changed_when: "'Terms and conditions accepted.' in license_burp.stdout or
        'License successfully installed and activated.' in license_burp.stdout"

    ### Configure tmux ###
    - name: Copy tmux config
      copy:
        src: files/.tmux.conf
        dest: "/home/{{ kali_user }}/.tmux.conf"
        owner: "{{ kali_user }}"
        group: "{{ kali_user }}"
        mode: 0640

    ### Firefox personalization ###
    - name: Get FireFox default profile
      command: firefox-esr -CreateProfile default -headless
      register: firefox_default_profile
      failed_when: "'Success' not in firefox_default_profile.stderr"

    - name: Set firefox_default_profile_dir fact
      set_fact:
        firefox_default_profile_dir: "{{ firefox_default_profile.stderr | regex_replace('.*at ''(.*)/prefs.js''$', '\\1') }}"

    - debug:
        var: firefox_default_profile_dir

    - name: Create user.js
      template:
        src: firefox/user.js.j2
        dest: "{{ firefox_default_profile_dir }}/user.js"
        mode: 0640
