---
# Playbook for Kali

## Personalize Kali
- hosts: kali
  roles:
    - ansible-role-vscode-extensions
  become: true
  become_user: "{{ kali_user }}"
  tasks:
    - name: Set home directory fact
      set_fact:
        kali_user_homedir: "{{ lookup('env','HOME') }}"

    ### Configure Gnome settings ###
    - name: Tweak Gnome settings
      command: "gsettings set {{ item }}"
      loop: "{{ gnome_settings }}"

    - name: Get current terminal profile
      command: gsettings get org.gnome.Terminal.ProfilesList default
      changed_when: false
      register: terminal_profile

    # Gnome terminal settings
    - name: Configure Terminal settings
      command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout | regex_replace('''') }}/ {{ item }}"
      loop: "{{ gnome_terminal_settings }}"

    ### Configure tmux ###
    - name: Copy tmux config
      copy:
        src: "files/tmux/.tmux.conf"
        dest: "{{ kali_user_homedir }}/.tmux.conf"
        mode: 0640

    ### Firefox personalization ###
    - name: Set firefox_default_profile_dir fact
      set_fact:
        firefox_default_profile_dir: "{{ kali_user_homedir }}/.mozilla/firefox/hacker.default"

    - name: Check if Firefox profile exists
      stat:
        path: "{{ firefox_default_profile_dir }}"
      register: firefox_profile

    - name: Create FireFox default profile
      command: "firefox-esr -CreateProfile \"default {{ firefox_default_profile_dir }}\""
      when: not firefox_profile.stat.exists

    - name: Create user.js for Firefox user preferences
      copy:
        src: "/opt/quieter-firefox/user.js"
        dest: "{{ firefox_default_profile_dir }}/user.js"
        remote_src: true
        mode: 0640

    ### SciTE user properties ###
    - name: Copy SciTE user properties
      copy:
        src: "files/scite/.SciTEUser.properties"
        dest: "{{ kali_user_homedir }}/.SciTEUser.properties"
        mode: 0640

    ### VS Code ###
    - name: Ensure VS Code user config directory exists
      file:
        path: "{{ kali_user_homedir }}/.config/Code/User"
        state: directory
        mode: 0700

    - name: Copy VS Code settings
      copy:
        src: files/vscode/settings.json
        dest: "{{ kali_user_homedir }}/.config/Code/User/settings.json"
        mode: 0640

    ### GDB ###
    - name: Clone GEF repo
      git:
        repo: "https://github.com/hugsy/gef.git"
        dest: "{{ kali_user_homedir }}/gef"
        force: true

    - name: Install optional modules for GEF
      pip:
        name:
          - capstone
          - ropper
          - unicorn
        executable: pip3

    - name: Copy gdb user properties
      copy:
        src: "files/gdb/.gdbinit"
        dest: "{{ kali_user_homedir }}/.gdbinit"
        mode: 0640
