---
# Playbook for Kali

## Personalize Kali
- hosts: kali
  roles:
    - role: ansible-role-vscode
      become: true
  tasks:
    ### Configure Gnome settings ###
    - name: Tweak Gnome settings
      command: "gsettings set {{ item }}"
      loop: "{{ gnome_settings }}"

    - name: Get current terminal profile
      command: gsettings get org.gnome.Terminal.ProfilesList default
      changed_when: false
      register: terminal_profile

    # Disable terminal background transparency
    - name: Configure Terminal settings
      command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout | regex_replace('''') }}/ use-transparent-background false"

    ### Configure tmux ###
    - name: Copy tmux config
      copy:
        src: files/.tmux.conf
        dest: "/home/{{ kali_user }}/.tmux.conf"
        owner: "{{ kali_user }}"
        group: "{{ kali_user }}"
        mode: 0640
