---
# Playbook to configure Kali VM
- hosts: kali
  tasks:
    - name: Update all packages to the latest version
      apt:
        update_cache: true
        upgrade: safe
  
    - name: Install packages
      apt:
        name: "{{ kali_packages }}"
        state: latest

# Install extra apps and files
- hosts: kali
  roles:
    - ansible-role-chromium
    - ansible-role-empire
    - ansible-role-hcxdumptool
    - ansible-role-hcxtools
    - ansible-role-nullinux
    - ansible-role-vscode
  tasks:
    - name: Clone git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "/opt/{{ item.name }}"
        version: "{{ item.version | default('master') }}"
      loop: "{{ git_repos | flatten(levels=1) }}"

    - name: Enable Postgresql service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Check msfdb status
      command: msfdb status
      register: msfdb_status

    - name: Initialize msfdb
      command: msfdb init
      when: "'No configuration file found' in msfdb_status.stdout"

    - name: Configure OpenSSL
      lineinfile:
        path: /etc/ssl/openssl.cnf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: "^MinProtocol ="
          line: "MinProtocol = None"
        - regexp: "^CipherStrings ="
          line: "CipherStrings = DEFAULT"

    - name: Create directory for BurpSuite extensions
      file:
        path: "{{ burpsuite_ext_dir }}"
        state: directory

    - name: Get JRuby sha256 checksum file
      get_url:
        url: "https://repo1.maven.org/maven2/org/jruby/jruby-complete/{{ burpsuite_jruby_version }}/jruby-complete-{{ burpsuite_jruby_version }}.jar.sha256"
        dest: "{{ burpsuite_ext_dir }}/jruby-complete.jar.sha256"

    - name: Download JRuby for Burp Suite
      get_url:
        url: "https://repo1.maven.org/maven2/org/jruby/jruby-complete/{{ burpsuite_jruby_version }}/jruby-complete-{{ burpsuite_jruby_version }}.jar"
        dest: "{{ burpsuite_ext_dir }}/jruby-complete.jar"
        checksum: "sha256:{{ jruby_checksums[0] }}"
      vars:
        jruby_checksums: "{{ lookup('file', '{{ burpsuite_ext_dir }}/jruby-complete.jar.sha256').splitlines() | list }}"

    - name: Get Jython sha1 checksum file
      get_url:
        url: "https://repo1.maven.org/maven2/org/python/jython-standalone/{{ burpsuite_jython_version }}/jython-standalone-{{ burpsuite_jython_version }}.jar.sha1"
        dest: "{{ burpsuite_ext_dir }}/jython-standalone.jar.sha1"

    - name: Download Jython for Burp Suite
      get_url:
        url: "https://repo1.maven.org/maven2/org/python/jython-standalone/{{ burpsuite_jython_version }}/jython-standalone-{{ burpsuite_jython_version }}.jar"
        dest: "{{ burpsuite_ext_dir }}/jython-standalone.jar"
        checksum: "sha1:{{ jython_checksums[0] }}"
      vars:
        jython_checksums: "{{ lookup('file', '{{ burpsuite_ext_dir }}/jython-standalone.jar.sha1').splitlines() | list }}"

    - name: Copy tmux config
      copy:
        src: files/.tmux.conf
        dest: /root/.tmux.conf
        owner: root
        group: root
        mode: 0640

    - name: Configure Gnome to less annoying defaults
      command: "gsettings set {{ item }}"
      loop:
        - "org.gnome.desktop.session idle-delay {{ gnome_idle_delay }}"
        - "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type '{{ gnome_sleep_type }}'"
        - "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type '{{ gnome_sleep_type }}'"

    - name: Configure proxychains
      lineinfile:
        path: "{{ item }}"
        regexp: "^proxy_dns"
        line: "#proxy_dns"
      loop:
        - "/etc/proxychains.conf"
        - "/etc/proxychains4.conf"
    
    # - name: Disable resume from swap. Quicker booting.
    #   lineinfile:
    #     path: "/etc/initramfs-tools/conf.d/resume"
    #     regexp: "RESUME="
    #     line: "RESUME=none"
    #   register: resume_swap
    
    # - name: Generate new initramfs
    #   command: update-initramfs -u
    #   when: resume_swap is changed
    
    # - name: reboot
    #   reboot:
    #   when: resume_swap is changed
