---
# Directory for BurpSuite extensions
burpsuite_ext_dir: "/root/BurpSuite"
burpsuite_jruby_version: "9.2.5.0"
burpsuite_jython_version: "2.7.1"

# Default idle delay (screen blanking) is 5 minutes (300)
gnome_idle_delay: 1800
# Default sleep type is suspend
gnome_sleep_type: "nothing"

# Git repositories to clone to /opt
git_repos:
  - name: fuzzdb
    repo: https://github.com/fuzzdb-project/fuzzdb.git
  - name: SecLists
    repo: https://github.com/danielmiessler/SecLists.git
  - name: PowerSploit
    repo: https://github.com/PowerShellMafia/PowerSploit.git
    version: dev
  - name: Stego-Toolkit
    repo: https://github.com/DominicBreuker/stego-toolkit.git
  - name: Responder
    repo: https://github.com/lgandx/Responder.git

# Packages to install
kali_packages:
  - aircrack-ng
  - bloodhound
  - crackmapexec
  - docker.io
  - docker-compose
  - dnsrecon
  - freerdp2-x11
  - git
  - gobuster
  - hostapd-wpe
  - libreoffice
  - masscan
  - open-vm-tools-desktop
  - patator
  - postgresql
  - proxychains4
  - python3
  - python3-pip
  - python3-venv
  - tmux
  - wifite
  - wireguard
  - xsel
  - zip

# Settings for VS Code
vscode_user: root
vscode_extensions:
  # Language extensions
  - ms-python.python
  - ms-vscode.go
  - ms-vscode.cpptools
  - ms-vscode.powershell
  - rebornix.ruby
  # Markdown extensions
  - yzhang.markdown-all-in-one
  - telesoho.vscode-markdown-paste-image
  # Utility extensions
  - hookyqr.beautify
