---
# Burp Suite settings
burpsuite_product_type: community
burpsuite_dir: /opt/BurpSuiteCommunity
burpsuite_cacert_path: "{{ burpsuite_extras_dir }}/PortSwigger_CA.der"
burpsuite_extras_dir: /opt/BurpSuiteExtras

gnome_settings:
  - "org.gnome.desktop.session idle-delay 1800"
  - "org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'"
  - "org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing'"
  - "org.gnome.desktop.interface gtk-theme 'Kali-X-Dark'"
  - "org.gnome.desktop.interface icon-theme 'Vibrancy-Kali-Dark'"
  - "org.gnome.shell.extensions.user-theme name 'Kali-X'"
  - "org.gnome.shell.extensions.dash-to-dock dock-fixed true"
  - "org.gnome.shell.extensions.dash-to-dock background-color '#1c2123'"
  - "org.gnome.shell.extensions.dash-to-dock force-straight-corner true"
  - "org.gnome.shell favorite-apps \"['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'firefox-esr.desktop', 'chromium.desktop', 'kali-burpsuite.desktop', 'org.keepassxc.KeePassXC.desktop', 'SciTE.desktop']\""

# Git repositories to clone to /opt
git_repos:
  - name: fuzzdb
    repo: https://github.com/fuzzdb-project/fuzzdb.git
  - name: Inveigh
    repo: https://github.com/Kevin-Robertson/Inveigh.git
  - name: PayloadsAllTheThings
    repo: https://github.com/swisskyrepo/PayloadsAllTheThings
  - name: Powermad
    repo: https://github.com/Kevin-Robertson/Powermad.git
  - name: PowerSploit
    repo: https://github.com/PowerShellMafia/PowerSploit.git
    version: dev
  - name: SecLists
    repo: https://github.com/danielmiessler/SecLists.git

kali_os_packages:
  - apparmor
  - apt-transport-https
  - chromium
  - cifs-utils
  - dnsutils
  - docker.io
  - docker-compose
  - dos2unix
  - expect
  - gdisk
  - gparted
  - gufw
  - iw
  - keepassxc
  - lvm2
  - macchanger
  - mlocate
  - default-mysql-client
  - openresolv
  - openvpn
  - p7zip-full
  - parted
  - php
  - postgresql
  - python-pip
  - python3-pip
  - rfkill
  - ruby
  - scite
  - screen
  - sqlite3
  - ssh
  - sudo
  - tcpdump
  - testdisk
  - tmux
  - ufw
  - unrar
  - wireguard
  - vim                              

# Packages to install
kali_tool_packages:
  - aircrack-ng
  - apache2
  - bloodhound
  - cadaver
  - cewl
  - creddump
  - dirb
  - dnsrecon
  - exe2hexbat
  - exploitdb
  - eyewitness
  - freerdp2-x11
  - ftp
  - gdb
  - gobuster
  - gpp-decrypt
  - hash-identifier
  - hydra
  - john
  - masscan
  - metasploit-framework
  - nasm
  - nbtscan-unixwiz
  - neo4j
  - netcat-traditional
  - netdiscover
  - nikto
  - nmap
  - onesixtyone
  - passing-the-hash
  - patator
  - proxychains4
  - python-impacket
  - responder
  - smbclient
  - smbmap
  - socat
  - sqlmap
  - tftp
  - wafw00f
  - webshells
  - weevely
  - wfuzz
  - whatweb
  - whois
  - wifiphisher
  - windows-binaries
  - wireshark
  - wpscan
  - xtightvncviewer

kali_user: hacker

misc_downloads:
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.0.0/pspy64
    dest: /opt/pspy/pspy64
    mode: "0755"
  - url: https://github.com/DominicBreuker/pspy/releases/download/v1.0.0/pspy64s
    dest: /opt/pspy/pspy64s
    mode: "0755"

# Settings for VS Code
vscode_user: hacker
vscode_extensions:
  # Language extensions
  - ms-python.python
  #- ms-vscode.go
  - ms-vscode.cpptools
  - ms-vscode.powershell
  - rebornix.ruby
  # Markdown extensions
  - yzhang.markdown-all-in-one
  - telesoho.vscode-markdown-paste-image
  # Utility extensions
  - hookyqr.beautify
